server:
  port: 5020

spring:
  application:
    name: user-data-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: admin
      password: admin

feign:
  client:
    config:
      default:
        readTimeout: 15000
        connectTimeout: 1500
verificationService:
  service:
    base:
      url: ${VERIFICATION_URL:http://localhost:5025}
    name: ${VERIFICATION_NAME:verificationService}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: ${HOSTNAME:localhost}

