spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER:localhost/auth-service/default}
  application:
    name: auth-service

server:
  port:

security:
  basic:
    enable:

  jwt:
    uri:
    header:
    prefix:
    expiration:
    secret:

  security:
    user:
      name:
      password:


feign:
  client:
    config:
      default:
        readTimeout:
        connectTimeout:
userData:
  service:
    base:
      url:
    name:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
    instance:
      hostname:

