server:
  port: 5020

spring:
  application:
    name: user-data-service
  datasource:
    url: jdbc:postgresql://ec2-54-74-156-137.eu-west-1.compute.amazonaws.com:5432/d98almhna1b5s9
    driver-class-name: org.postgresql.Driver
    username: mhravsyezterfd
    password: 66a7c6f5bb75d08199117dcf3a2dcf4f159ee38be403e511839b8a1fd48b0661
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    user:
      name: admin
      password: admin

feign:
  client:
    config:
      default:
        readTimeout: 15000
        connectTimeout: 1500
verificationService:
  service:
    base:
      url: ${VERIFICATION_URL:https://hivein-verification.herokuapp.com}
    name: ${VERIFICATION_NAME:verificationService}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://hivein-registry.herokuapp.com/eureka}
    instance:
      hostname: ${HOSTNAME:hivein-registry}

