security:
  basic:
    enable:

  jwt:
    uri:
    header:
    prefix:
    expiration:
    secret:

eureka:
  client:
    register-with-eureka:
    fetch-registry:
    service-url:
      defaultZone:
    instance:
      hostname:

feign:
  client:
    config:
      default:
        readTimeout:
        connectTimeout:
userData:
  service:
    base:
      url:
    name:

zuul:
  sensitive-headers:
  routes:
    auth:
      url:
    user:
      url:
    register:
      url:
    verify:
      url:
  host:
    connect-timeout-millis:
    socket-timeout-millis:
