server:
  port: 5000

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: hubabubamarakuya

spring:
  application:
    name: auth-service

  security:
    user:
      name: admin
      password: admin


feign:
  client:
    config:
      default:
        readTimeout: 15000
        connectTimeout: 5000
userData:
  service:
    base:
      url: https://hivein-userdata.herokuapp.com/
    name: userData

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://hivein-registry.herokuapp.com/eureka}
    instance:
      hostname: ${HOSTNAME:hivein-registry}

