server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APP_NAME:api-gateway}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://hivein-registry.herokuapp.com/eureka}
    instance:
      hostname: ${HOSTNAME:hivein-registry}

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    auth:
      url: ${AUTH_SERVICE:https://hivein-authentication.herokuapp.com/auth}
    user:
      url: ${USER_SERVICE:https://hivein-userdata.herokuapp.com/user}
    register:
      url: ${USER_SERVICE:https://hivein-userdata.herokuapp.com/register}
    verify:
      url: ${VERIFICATION_SERVICE:https://hivein-verification.herokuapp.com/verify}
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000

security:
  oauth2:
    resource:
      jwt:
        key-value: 333sektumsempraaladinabrakadabra333
        header: Authorization
        prefix: Bearer
