spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Sakerini/Hivein-Config
          username: ${username:acc}
          password: ${password:pass}
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://hivein-registry.herokuapp.com/eureka}
    instance:
      hostname: ${HOSTNAME:hivein-registry}

