server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APP_NAME:api-gateway}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: ${HOSTNAME:localhost}

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    auth:
      url: ${AUTH_SERVICE:http://localhost:5000}
    user:
      url: ${USER_SERVICE:http://localhost:5020}
    verification:
      url: ${VERIFICATION_SERVICE:http://localhost:5025}
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 5000

security:
  oauth2:
    resource:
      jwt:
        key-value: JwtSecretKey
