server:
  port: 5025

spring:
  application:
    name: verification-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: ${SMTP:smtp.gmail.com}
    port: ${PORT:587}
    username: chat.hivein@gmail.com
    password:
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

site:
  base:
    url:
      https: ${SITE_URL:http://localhost:8080}

security:
  jwt:
    expiration: ${TOKEN_EXPIRATION:3600}
    secret: ${JWT_SECRET:JwtSecretKey}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostname: ${HOSTNAME:localhost}

